# <center>Assignment_04</center>
**<center>WEB SCRAPING</center>**

In [1]:
# Let's import all required Libraries:
from selenium.webdriver.common.keys import Keys
import selenium # Library that is used to work with selenium.
from selenium import webdriver # Importing webdriver module from selenium to open automated chrome window
import pandas as pd # to create Dataframe
from selenium.webdriver.common.by import By # importing inbuilt class by
import warnings # to ignore any sort of warning
warnings.filterwarnings("ignore")

import requests
import re # regular expression

In [2]:
# importing delays:

import time # used to stop engine for few seconds
from selenium.webdriver.support.ui import WebDriverWait # used to stop engine for few seconds
from selenium.webdriver.support import expected_conditions as EC # EC contains a set of predefined conditions to use with WebDriverWait.

In [3]:
# importing exceptions:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException 
from selenium.common.exceptions import ElementNotVisibleException 
from selenium.common.exceptions import ElementNotInteractableException
from selenium.common.exceptions import SessionNotCreatedException
from selenium.common.exceptions import TimeoutException

# Question 1.

Scrape the details of most viewed videos on YouTube from Wikipedia: 

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos 
You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [4]:
# Connecting to webdriver
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")
time.sleep(1)

# Opening 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos' in chrome browser:
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [5]:
# Empty list for scraping data
Rank =[]
Name =[]
Artist =[]
Upload_date=[]
Views=[]

# Extracting 'Rank':
try:
    rank=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
except StaleElementReferenceException:
    Rank.append('NA')
    
# Extracting Name:
try:
    name=driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in name:
        Name.append(i.text)
except NoSuchElementExceptionhElementException:
    Name.append('NA')
except StaleElementReferenceException:
    Name.append('NA')
    
# Extracting Artist:
try:
    artist=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist:
        Artist.append(i.text)
except NoSuchElementExceptionhElementException:
    Artist.append('NA')
except StaleElementReferenceException:
    Artist.append('NA')

# Extracting Upload date:
try:
    upload_date=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date:
        Upload_date.append(i.text)
except NoSuchElementExceptionhElementException:
    Upload_date.append('NA')
except StaleElementReferenceException:
    Upload_date.append('NA') 

# Extracting Views:
try:
    views=driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views:
        Views.append(i.text)
except NoSuchElementExceptionhElementException:
    Views.append('NA')
except StaleElementReferenceException:
    Views.append('NA')

In [6]:
# Dataframe for scrap data:

Wiki_YT=pd.DataFrame({'Rank':Rank,'Video Name':Name,'Uploader':Artist,'Views (in Billons)':Views,'Upload Date':Upload_date})
print('\033[1m'+'Most Viewed Video on YouTube from Wikipedia :'+'\033[0m')
Wiki_YT = Wiki_YT.set_index('Rank')
Wiki_YT

Most Viewed Video on YouTube from Wikipedia :

,Video Name,Uploader,Views (in Billons),Upload Date
Rank,,,,
1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,11.83,"June 17, 2016"
2.,"""Despacito""[7]",Luis Fonsi,8.02,"January 12, 2017"
3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.54,"October 8, 2016"
4.,"""Shape of You""[15]",Ed Sheeran,5.86,"January 30, 2017"
5.,"""Bath Song""[17]",Cocomelon – Nursery Rhymes,5.81,"May 2, 2018"
6.,"""See You Again""[18]",Wiz Khalifa,5.71,"April 6, 2015"
7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.04,"March 6, 2014"
8.,"""Uptown Funk""[24]",Mark Ronson,4.77,"November 19, 2014"
9.,"""Learning Colors – Colorful Eggs on a Farm""[25]",Miroshka TV,4.74,"February 27, 2018"
10.,"""Wheels on the Bus""[26]",Cocomelon – Nursery Rhymes,4.69,"May 24, 2018"
11.,"""Gangnam Style""[27]",Psy,4.62,"July 15, 2012"
12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.52,"January 31, 2012"
13.,"""Dame Tu Cosita""[33]",El Chombo,4.15,"April 5, 2018"
14.,"""Sugar""[34]",Maroon 5,3.79,"January 14, 2015"
15.,"""Roar""[35]",Katy Perry,3.69,"September 5, 2013"
16.,"""Counting Stars""[36]",OneRepublic,3.69,"May 31, 2013"
17.,"""Axel F""[37]",Crazy Frog,3.63,"June 16, 2009"
18.,"""Sorry""[38]",Justin Bieber,3.61,"October 22, 2015"
19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.52,"October 7, 2014"
20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.44,"June 25, 2018"
21.,"""Dark Horse""[41]",Katy Perry,3.40,"February 20, 2014"
22.,"""Faded""[42]",Alan Walker,3.38,"December 3, 2015"
23.,"""Girls Like You""[43]",Maroon 5,3.35,"May 31, 2018"
24.,"""Let Her Go""[44]",Passenger,3.35,"July 25, 2012"
25.,"""Waka Waka (This Time for Africa)""[45]",Shakira,3.34,"June 4, 2010"
26.,"""Perfect""[46]",Ed Sheeran,3.31,"November 9, 2017"
27.,"""Bailando""[47]",Enrique Iglesias,3.30,"April 11, 2014"
28.,"""Lean On""[48]",Major Lazer,3.29,"March 22, 2015"
29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.24,"January 26, 2018"
30.,"""Shake It Off""[50]",Taylor Swift,3.23,"August 18, 2014"

In [7]:
# Closing of Automated Window:

driver.close()

# Question 2.

Scrape the details team India’s international fixtures from bcci.tv.

Url = https://www.bcci.tv
    
You need to find following details:
    
A) Match title (I.e. 1st ODI) 

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")
time.sleep(1)

# Opening 'www.bcci.tv' in chrome browser:
url='https://www.bcci.tv/'
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [5]:
# Opening fixtures webpage through browser:
fixtures = driver.find_element(By.XPATH,'//*[@id="navigation"]/ul[1]/li[2]/a')
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))

In [15]:
# Creating empty list:
Title = [] 
Series = [] 
Place = [] 
Date = [] 
Time = [] 

   
# Scraping Match title:
try:
    title=driver.find_elements(By.XPATH,"//span[@class='matchOrderText ng-binding ng-scope']")
    for i in title:
        Title.append(i.text.replace(' -','')) 
except NoSuchElementException:
    Title.append('NA')
        
# Scraping Series:
try:
    series=driver.find_elements(By.XPATH,"//span[@class='ng-binding']")
    for i in series:
        Series.append(i.text)
except NoSuchElementException:
    Series.append('NA')
        
# Scraping Place:
try:
    place=driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']")
    for i in place:
        Place.append(i.text.split('-')[-1:])
except NoSuchElementException:
    Place.append('NA')
        
# Scraping date:
try:
    date=driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
    for i in date:
        Date.append(i.text)
except NoSuchElementException:
    Date.append('NA')
        
# Scraping Time:

try:
    time=driver.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']")
    for i in time:
        Time.append(i.text)
except NoSuchElementException:
    Time.append('NA')

In [16]:
len(Title),len(Series),len(Place),len(Date),len(Time)

(8, 8, 8, 8, 8)

In [17]:
# Creating Dataframe for scrapped data:
Cricket=pd.DataFrame({'Match Title':Title,'Tournament':Series,'Venue':Place,'Date':Date,'Time':Time})
Cricket

,Match Title,Tournament,Venue,Date,Time
0,3rd ODI,INDIA TOUR OF BANGLADESH ODI SERIES 2022-23,"[ Zahur Ahmed Chowdhury Stadium, Chattogram]",10 DEC 2022,11:30 AM IST
1,2nd T20I,AUSTRALIA WOMEN TOUR OF INDIA 2022,"[ DY Patil Stadium, NAVI MUMBAI]",11 DEC 2022,7:00 PM IST
2,1st Test,INDIA TOUR OF BANGLADESH TEST SERIES 2022-23,"[ Zahur Ahmed Chowdhury Stadium, Chattogram]",14 DEC 2022,9:30 AM IST
3,3rd T20I,AUSTRALIA WOMEN TOUR OF INDIA 2022,"[ CCI, Mumbai]",14 DEC 2022,7:00 PM IST
4,4th T20I,AUSTRALIA WOMEN TOUR OF INDIA 2022,"[ CCI, Mumbai]",17 DEC 2022,7:00 PM IST
5,5th T20I,AUSTRALIA WOMEN TOUR OF INDIA 2022,"[ CCI, Mumbai]",20 DEC 2022,7:00 PM IST
6,2nd Test,INDIA TOUR OF BANGLADESH TEST SERIES 2022-23,"[ Shere Bangla National Stadium, Mirpur, Dhaka]",22 DEC 2022,9:30 AM IST
7,1st T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"[ Wankhede Stadium, Mumbai]",3 JAN 2023,7:30 PM IST

In [18]:
# Closing of Automated Window:

driver.close()

# Question 3. 

Scrape the details of selenium exception from guru99.com.

Url = https://www.guru99.com/
    
You need to find following details:
    
A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [32]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://www.guru99.com' in chrome browser:
url='https://www.guru99.com/'
driver.get(url)
driver.maximize_window()

In [33]:
# Selecting Selenium option from website
Selenium=driver.find_element(By.XPATH,'//*[@id="java_technologies"]/li[3]/a')
try:
    Selenium.click()
except ElementNotInteractableException:
    driver.get(Selenium.get_attribute('href'))
    Selenium.click()

In [34]:
# Selecting Selenium Exception handling option from website
Selenium_Exception=driver.find_element(By.XPATH,'//*[@id="post-193"]/div/div/table[5]/tbody/tr[34]/td[1]/a')
try:
    Selenium_Exception.click()
except ElementNotInteractableException:
    driver.get(Selenium_Exception.get_attribute('href'))
    Selenium.click()

In [48]:
# Extracting Exception Name:

Name =[] # Creating Empty list

try:
    name=driver.find_elements(By.XPATH,'//*[@id="post-1953"]/div/div/p/strong')
    for i in name:
        Name.append(i.text.split(' ')[-1][0:-1])
except NoSuchElementException:
    Name.append('NA')
    
Name=Name[0:41]
Name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateException',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [53]:
# Extracting Description:

Description=[] # Creating Empty list
try:
    description=driver.find_elements(By.XPATH,'//*[@id="post-1953"]/div/div/p')
    for i in description:
        Description.append(i.text.split(':')[-1])
except NoSuchElementException:
    Description.append('NA')
Description = Description[0:41]
Description

[' This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 ' This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 ' This Exception occurs if an element could not be found.',
 ' This Exception occurs if the frame target to be switched to does not exist.',
 ' This Exception occurs when you switch to no presented alert.',
 ' This Exception occurs if the window target to be switch does not exist.',
 ' This Selenium exception occurs happens when the web element is detached from the current DOM.',
 ' The WebDriver is acting after you quit the browser.',
 ' Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
 ' This Exception takes place when the WebDriver is acting right after you close the browser.',
 ' This type of Exception takes place when there is a disconnection in the driver.',
 ' The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 ' This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 ' This happens while interacting with the Firefox extension or the remote driver server.',
 ' Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 ' This expectation will occur when IME engine activation has failed.',
 ' It takes place when IME support is unavailable.',
 ' Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 ' It occurs when an argument does not belong to the expected type.',
 ' This happens when you try to add a cookie under a different domain instead of current URL.',
 ' This type of Exception matches an interacting operation that is not valid.',
 ' It occurs when command can’t be finished when the element is invalid.',
 ' This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 ' This occurs when the frame or window target to be switched does not exist.',
 ' This issue occurs while executing JavaScript given by the user.',
 ' It occurs when you afford to get the session when the session is not created.',
 ' This kind of Exception occurs when the attribute of an element could not be found.',
 ' It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 ' ContextAware does mobile device testing.',
 ' This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 ' This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 ' This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 ' It is not possible to capture a screen.',
 ' It happens when a new session could not be successfully created.',
 ' This occurs if a driver is unable to set a cookie.',
 ' Happens if a support class did not get a web element as expected.',
 ' This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 ' It occurs when there is the appearance of an unexpected alert.',
 ' This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 ' This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 ' This occurs when remote WebDriver doesn’t send valid commands as expected.']

In [54]:
len(Description),len(Name)

(41, 41)

In [56]:
# Dataframe for scrap data
Exception=pd.DataFrame({'Exception Type':Name,'Description':Description})
Exception

,Exception Type,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when a...
1,ElementNotSelectableException,This Selenium exception occurs when an elemen...
2,NoSuchElementException,This Exception occurs if an element could not...
3,NoSuchFrameException,This Exception occurs if the frame target to ...
4,NoAlertPresentException,This Exception occurs when you switch to no p...
5,NoSuchWindowException,This Exception occurs if the window target to...
6,StaleElementReferenceException,This Selenium exception occurs happens when t...
7,SessionNotFoundException,The WebDriver is acting after you quit the br...
8,TimeoutException,Thrown when there is not enough time for a co...
9,WebDriverException,This Exception takes place when the WebDriver...
10,ConnectionClosedException,This type of Exception takes place when there...
11,ElementClickInterceptedException,The command may not be completed as the eleme...
12,ElementNotInteractableException,This Selenium exception is thrown when any el...
13,ErrorInResponseException,This happens while interacting with the Firef...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if...
15,ImeActivationFailedException,This expectation will occur when IME engine a...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certi...
18,InvalidArgumentException,It occurs when an argument does not belong to...
19,InvalidCookieDomainException,This happens when you try to add a cookie und...
20,InvalidCoordinatesException,This type of Exception matches an interacting...
21,InvalidElementStateException,It occurs when command can’t be finished when...
22,InvalidSessionIdException,This Exception took place when the given sess...
23,InvalidSwitchToTargetException,This occurs when the frame or window target t...
24,JavascriptException,This issue occurs while executing JavaScript ...
25,JsonException,It occurs when you afford to get the session ...
26,NoSuchAttributeException,This kind of Exception occurs when the attrib...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching...
30,NotFoundException,This Exception is a subclass of WebDriverExce...
31,RemoteDriverServerException,This Selenium exception is thrown when the se...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be su...
34,UnableToSetCookieException,This occurs if a driver is unable to set a co...
35,UnexpectedTagNameException,Happens if a support class did not get a web ...
36,UnhandledAlertException,This expectation occurs when there is an aler...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
38,UnknownMethodException,This Exception happens when the requested com...
39,UnreachableBrowserException,This Exception occurs only when the browser i...
40,UnsupportedCommandException,This occurs when remote WebDriver doesn’t sen...

In [57]:
# Closing of Automated Window:

driver.close()

# Question 4. 

Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(18-19)- at current prices

D) GSDP(19-20)- at current prices

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [4]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'statisticstimes.com' in chrome browser:
url='https://www.statisticstimes.com/'
driver.get(url)
driver.maximize_window()

In [5]:
# Clicking on India under ecomony section
India=driver.find_element(By.XPATH,'//div[@class="dropdown"][2]/div/a[3]')
try:
    India.click()
except ElementNotInteractableException:
    driver.get(India.get_attribute('href'))

# Clicking Indian State GDP
state = driver.find_element(By.XPATH,'//ul[@style="list-style-type:none;margin-left:20px;"]/li[1]/a')
try:
    state.click()
except ElementNotInteractableException:
    driver.get(state.get_attribute('href'))

In [6]:
# Creating Empty lists
Rank =[]
State =[]
GDSP_19_20=[]
GDSP_18_19 =[]
Share =[]
GDP =[]

# Extracting Rank via Xpath
try:
    rank=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[1]')
    for i in rank:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('NA')
    
# Extracting state name via Xpath
try:
    state=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]')
    for i in state:
        State.append(i.text)
except NoSuchElementException:
    State.append('NA')
    
# Extracting GDSP 19-20 via Xpath
try:
    gdsp_19_20=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]')
    for i in gdsp_19_20:
        GDSP_19_20.append(i.text)
except NoSuchElementException:
    GDSP_19_20.append('NA')
    
# Extracting GDSP 18-19 via Xpath
try:
    gdsp_18_19=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[4]')
    for i in gdsp_18_19:
        GDSP_18_19.append(i.text)
except NoSuchElementException:
    GDSP_18_19.append('NA')
    
# Extracting share in billons via Xpath
try:
    share=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[5]')
    for i in share:
        Share.append(i.text)
except NoSuchElementException:
    Share.append('NA')

# Extracting GDP via Xpath
try:
    gdp=driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[6]')
    for i in gdp:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('NA')

In [7]:
len(Rank),len(State),len(GDSP_19_20),len(GDSP_18_19),len(Share),len(GDP)

(33, 33, 33, 33, 33, 33)

In [9]:
# Dataframe for scrap data
Statewise_GDP=pd.DataFrame({'Rank':Rank,'State':State,'GDSP 19-20':GDSP_19_20,'GDSP 18-19':GDSP_18_19,
                            'Share':Share,'GDP (in Billions)':GDP})
Statewise_GDP = Statewise_GDP.set_index('Rank')
Statewise_GDP

,State,GDSP 19-20,GDSP 18-19,Share,GDP (in Billions)
Rank,,,,,
1,Maharashtra,-,"2,632,792",13.94%,399.921
2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
4,Gujarat,-,"1,502,899",7.96%,228.290
5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
7,Rajasthan,"1,020,989","942,586",4.99%,143.179
8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
9,Telangana,"969,604","861,031",4.56%,130.791
10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
11,Kerala,-,"781,653",4.14%,118.733
12,Delhi,"856,112","774,870",4.10%,117.703
13,Haryana,"831,610","734,163",3.89%,111.519
14,Bihar,"611,804","530,363",2.81%,80.562
15,Punjab,"574,760","526,376",2.79%,79.957
16,Odisha,"521,275","487,805",2.58%,74.098
17,Assam,-,"315,881",1.67%,47.982
18,Chhattisgarh,"329,180","304,063",1.61%,46.187
19,Jharkhand,"328,598","297,204",1.57%,45.145
20,Uttarakhand,-,"245,895",1.30%,37.351
21,Jammu & Kashmir,-,"155,956",0.83%,23.690
22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
23,Goa,"80,449","73,170",0.39%,11.115
24,Tripura,"55,984","49,845",0.26%,7.571
25,Chandigarh,-,"42,114",0.22%,6.397
26,Puducherry,"38,253","34,433",0.18%,5.230
27,Meghalaya,"36,572","33,481",0.18%,5.086
28,Sikkim,"32,496","28,723",0.15%,4.363
29,Manipur,"31,790","27,870",0.15%,4.233
30,Nagaland,-,"27,283",0.14%,4.144
31,Arunachal Pradesh,-,"24,603",0.13%,3.737
32,Mizoram,"26,503","22,287",0.12%,3.385
33,Andaman & Nicobar Islands,-,-,-,-

In [10]:
# Closing of Automated Window:

driver.close()

# Question 5. 

Scrape the details of trending repositories on Github.com.

Url = https://github.com/
    
You have to find the following details:
    
A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [4]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url='https://github.com/'
driver.get(url)
driver.maximize_window()

In [5]:
# Clicking on trending option:
trending = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
try:
    trending.click()
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

In [6]:
# Scraping Repositority Title
Title=[]

try:
    title=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
    for i in title:
        Title.append(i.text)
except NoSuchElementException:
    Title.append('NA')

In [12]:
Title

['shinework / photoshot',
 'wangrongding / wechat-bot',
 'ange-yaghi / engine-sim',
 'f / awesome-chatgpt-prompts',
 'eatmoreapple / openwechat',
 'skydoves / chatgpt-android',
 'louislam / uptime-kuma',
 'mohammadpz / pytorch_forward_forward',
 'calistus-igwilo / nitda-blockchain-scholarship',
 'fuergaosi233 / wechat-chatgpt',
 'humanloop / awesome-chatgpt',
 'GitHubDaily / GitHubDaily',
 'lensterxyz / lenster',
 'tw93 / Pake',
 'Stability-AI / stablediffusion',
 'MicrosoftDocs / azure-docs',
 'exaloop / codon',
 'deepmind / dramatron',
 'colinhacks / zod',
 'PlexPt / chatgpt-java',
 'kingoflolz / mesh-transformer-jax',
 'hwchase17 / langchain',
 'AutumnWhj / ChatGPT-wechat-bot',
 'awslabs / eks-node-viewer']

In [13]:
len(Title)

24

In [7]:
# Scraping Description
Description=[]

try:
    description=driver.find_elements(By.XPATH,"//article[@class='Box-row']/p")
    for i in description:
        Description.append(i.text)
except NoSuchElementException:
    Description.append('NA')

In [15]:
Description

['🤖一个基于OpenAi ChatGPT + WeChaty 实现的微信机器人 ，可以用来帮助你自动回复微信消息，或者管理微信群/好友，检测僵尸粉等...',
 'Combustion engine simulator that generates realistic audio.',
 'This repo includes ChatGPT promt curation to use ChatGPT better.',
 'golang版微信SDK',
 "📱 ChatGPT Android demonstrates OpenAI's ChatGPT on Android with Stream Chat SDK for Compose.",
 'A fancy self-hosted monitoring tool',
 "Implementation of Hinton's forward-forward (FF) algorithm - an alternative to back-propagation",
 'Course materials for the NITDA Blockchain Scholarship',
 'Use ChatGPT On Wechat via wechaty',
 'Curated list of awesome tools, demos, docs for ChatGPT and GPT-3',
 '坚持分享 GitHub 上高质量、有趣实用的开源技术教程、开发者工具、编程网站、技术资讯。A list cool, interesting projects of GitHub.',
 'Lenster is a decentralized, and permissionless social media app built with Lens Protocol 🌿',
 '🤱🏻 A simple way to make any web page a desktop application using Rust. 🤱🏻 很简单的用 Rust 打包网页生成很小的桌面 App',
 'High-Resolution Image Synthesis with Latent Diffusion Models',
 'Open source documentation of Microsoft Azure',
 'A high-performance, zero-overhead, extensible Python compiler using LLVM',
 'Dramatron uses large language models to generate coherent scripts and screenplays.',
 'TypeScript-first schema validation with static type inference',
 "ChatGPT Java SDK. Lightweight package for interacting with ChatGPT's API by OpenAI. Uses reverse engineered official API. ChatGPT 聊天机器人 Java 版. 开箱即用.",
 'Model parallel transformers in JAX and Haiku',
 '⚡ Building applications with LLMs through composability ⚡',
 'ChatGPT for wechat',
 'EKS Node Viewer']

In [14]:
len(Description)

23

In [8]:
# Creating Empty lists    
URL = []
Contri_count = []
Lang_used = []
# Scraping repositories URL:

link = driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a')
for i in link:
    URL.append(i.get_attribute('href'))
time.sleep(1)

# Entering into each repository to fetch 'contributors count' & 'languages used'

for i in URL:
    driver.get(i)
    lang=[] # making empty list
    time.sleep(1)
    
    # scraping contributors count
    
    try:
        count = driver.find_element(By.XPATH,"//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contri_count.append(count.text)
    except NoSuchElementException:
        Contri_count.append('-')
    time.sleep(1)
    
    # scraping languages used
    
    language = driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
    if language:    
        for i in language:
            lang.append(i.text)
    else:
        lang.append('-')
    Lang_used.append(lang)
time.sleep(1)

In [17]:
Contri_count

['-',
 '5',
 '6',
 '24',
 '15',
 '2',
 '209',
 '2',
 '-',
 '23',
 '7',
 '3',
 '53',
 '15',
 '11',
 '5,000+',
 '4',
 '3',
 '182',
 '-',
 '23',
 '32',
 '3',
 '6']

In [16]:
len(Contri_count)

24

In [19]:
Lang_used

[['TypeScript'],
 ['JavaScript', 'Dockerfile', 'Shell'],
 ['C++', 'CMake', 'C'],
 ['-'],
 ['Go', 'Python'],
 ['Kotlin'],
 ['JavaScript', 'Vue', 'SCSS', 'TypeScript', 'Shell', 'Dockerfile'],
 ['Python'],
 ['-'],
 ['TypeScript', 'Python', 'Dockerfile', 'Shell'],
 ['-'],
 ['-'],
 ['TypeScript'],
 ['Rust'],
 ['Python'],
 ['PowerShell'],
 ['C++', 'Python'],
 ['Jupyter Notebook'],
 ['TypeScript', 'JavaScript'],
 ['Java'],
 ['Python', 'Jupyter Notebook', 'Shell', 'Dockerfile'],
 ['Python', 'Makefile'],
 ['TypeScript', 'JavaScript', 'Dockerfile', 'Shell'],
 ['Go', 'Makefile']]

In [18]:
len(Lang_used)

24

In [20]:
# Closing of Automated Window:

driver.close()

# Question 6. 

Scrape the details of top 100 songs on billboard.com.

Url = https://www.billboard.com/
    
You have to find the following details:
    
A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [59]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url='https://www.billboard.com/'
driver.get(url)
driver.maximize_window()

In [62]:
# Clicking on hot 100 option
hot_100=driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/div[8]/div/div/div/ul/li[1]/ul/li[2]/a')
try:
    hot_100.click()
except ElementNotInteractableException:
    driver.get(hot_100.get_attribute('href'))

In [70]:
# Scraping Song Name:
Song = [] # Creating Empty List
try:
    song = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]')
    for i in song:
        Song.append(i.text.split('\n')[0])
except NoSuchElementException:
    Song.append('NA')

# Scraping Artist name:    
Artist =[] # Creating Empty List
try:
    artist = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]')
    for i in artist:
        Artist.append(i.text.split('\n')[1])
except NoSuchElementException:
    Artist.append('NA')

# Scraping Last week rank:
Last_Week_rank =[] # Creating Empty List
try:
    last_Week_rank = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]')
    for i in last_Week_rank:
        Last_Week_rank.append(i.text.split('\n')[2])
except NoSuchElementException:
    Last_Week_rank.append('NA')

# Scraping Peak rank:
Peak_rank =[] # Creating Empty List
try:
    peak_rank = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]')
    for i in peak_rank:
        Peak_rank.append(i.text.split('\n')[3])
except NoSuchElementException:
    Peak_rank.append('NA')

# Scraping Weeks on board:
Weeks =[] # Creating Empty List
try:
    weeks = driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]')
    for i in weeks:
        Weeks.append(i.text.split('\n')[4])
except NoSuchElementException:
    Weeks.append('NA')

In [71]:
Billboard=pd.DataFrame({'Song_Name':Song,
                'Artist_Name':Artist,
                'Last_week_rank':Last_Week_rank,
                'Peak':Peak_rank,
                'Weeks_on_chart':Weeks})
print('\033[1m'+'Billboard Hot 100 Songs :'+'\033[0m')
Billboard

Billboard Hot 100 Songs :

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,Anti-Hero,Taylor Swift,1,1,6
1,All I Want For Christmas Is You,Mariah Carey,5,1,54
2,Rockin' Around The Christmas Tree,Brenda Lee,6,2,48
3,Unholy,Sam Smith & Kim Petras,3,1,10
4,Jingle Bell Rock,Bobby Helms,9,3,45
...,...,...,...,...,...
95,Someday At Christmas,Lizzo,-,96,1
96,Vigilante Shit,Taylor Swift,73,10,6
97,Forget Me,Lewis Capaldi,-,95,6
98,"Going, Going, Gone",Luke Combs,98,98,3
99,Miss You,Oliver Tree & Robin Schulz,91,84,6

In [72]:
# Closing of Automated Window:

driver.close()

# Question 7. 

Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [60]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url = 'https://www.naukri.com/hr-recruiters-consultants '
driver.get(url)
driver.maximize_window()

In [61]:
# locating Search bar via Xpath
Search=driver.find_element(By.XPATH,"//*[@id='skill']/div[1]/div[2]/input")

# Sending data science as key in search bar
Search.send_keys("Data Science")

#clicking on search button
button=driver.find_element(By.XPATH,'//*[@id="qsbFormBtn"]')
button.click()

In [62]:
# Creating Empty List
Name =[]
Designation =[]
Company =[]
Skill =[]
Location =[]

# Scraping  Name
try:
    name=driver.find_elements(By.XPATH,'//a[@class="ellipsis"]/span')
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
        Name.append('NA')

# Scraping Designation
try:
    designation=driver.find_elements(By.XPATH,'//p[@class="highlightable"]/span[1]')
    for i in designation:
        Designation.append(i.text)
except NoSuchElementException:
    Designation.append('NA')
    
# Scraping Company
try:
    company=driver.find_elements(By.XPATH,'//a[@class="ellipsis"][2]')
    for i in company:
        Company.append(i.text)
except NoSuchElementException:
    Company.append('NA')
# Scraping skill for they hire
try:
    skill=driver.find_elements(By.XPATH,'//div[@class="hireSec highlightable"]')
    for i in skill:
        Skill.append(i.text)
except NoSuchElementException:
    Skill.append('NA')

In [63]:
# Scraping location Name

Location =[]
try:
    location=driver.find_elements(By.CLASS_NAME,'highlightable')
    for i in location:
        Location.append(i.text.split('\n')) # .split('\n')
except NoSuchElementException:
    Location.append('NA') 
    
Location=Location[::2] # getting EVEN indexed Elements 

new_list = [sublist[-1] for sublist in Location] # getting last element from each list in the nested list.

# replacing the falce data with '-'
replacing = {'Nanoprecise Sci Corp':'-', 'Granular.ai':'-'} 
Location = [replacing.get(n, n) for n in new_list]

In [64]:
len(Name),len(Designation),len(Company),len(Skill),len(Location)

(50, 50, 50, 50, 50)

In [65]:
Naukri=pd.DataFrame({})
Naukri['Name']=Name
Naukri['Designation']=Designation
Naukri['Company']=Company
Naukri['Skills I Hire for']=Skill
Naukri['Location']=Location
Naukri

,Name,Designation,Company,Skills I Hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
34,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",-
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad

In [66]:
# Closing of Automated Window:

driver.close()

# Question 8. 

Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
    
You have to find the following details:
    
A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [113]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
driver.maximize_window()

In [114]:
# Creating Empty Lists
Book =[]
Author =[]
Volumes_sold =[]
Publisher =[]
Genre =[]

In [115]:
# Scraping Book name
try:
    book=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book:
        Book.append(i.text)
except NoSuchElementException:
    Book.append('NA')
    
# Scraping Book author's via Xpath
try:
    author=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for i in author:
        Author.append(i.text)
except NoSuchElementException:
    Author.append('NA')
    
# Scraping Volumes sold via Xpath
try:
    sold=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for i in sold:
        Volumes_sold.append(i.text)
except NoSuchElementException:
    Volumes_sold.append('NA')
    
# Scraping publisher via xPath
try:
    publisher=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for i in publisher:
        Publisher.append(i.text)
except NoSuchElementException:
    Publisher.append('NA')
    
# Scraping Genre via Xpath
try:
    genre=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')

In [116]:
#creating dataframe
Top_Books=pd.DataFrame({"Book Title":Book,
                "Author Name":Author,
                'Volumes sold':Volumes_sold,
                'Publisher':Publisher,
                'Genre':Genre})
print('\033[1m'+'Best Selling Books of All Time List by The Guardian  :'+'\033[0m')
Top_Books

Best Selling Books of All Time List by The Guardian  :

,Book Title,Author Name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [117]:
# Closing of Automated Window:

driver.close()

# Question 9. 

Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/
        
You have to find the following details:
    
A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [118]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)
driver.maximize_window()

In [119]:
# Creating Empty List
Name =[]
Year_Span=[]
Genre =[]
Run_Time =[]
Ratings =[]
Votes =[]

In [120]:
# Scraping Name via Xpath
try:
    name=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in name:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('NA')

# Scraping Year span via Xpath
try:
    year=driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/span[2]")
    for i in year:
        Year_Span.append(i.text)
except NoSuchElementException:
    Year_Span.append('NA')
    
# Scraping Genre via Xpath
try:
    genre=driver.find_elements(By.XPATH,"//span[@class='genre']")
    for i in genre:
        Genre.append(i.text)
except NoSuchElementException:
    Genre.append('NA')
    
# Scraping RunTime via Xpath
try:
    runtime=driver.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in runtime:
        Run_Time.append(i.text)
except NoSuchElementException:
    Run_Time.append('NA')

# Scraping Ratings via Xpath
try:
    ratings=driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']/span[2]")
    for i in ratings:
        Ratings.append(i.text)
except NoSuchElementException:
    Ratings.append('NA')

# Scraping Votes via Xpath
try:
    votes=driver.find_elements(By.XPATH,"//span[@name='nv']")
    for i in votes:
        Votes.append(i.text)
except NoSuchElementException:
    Votes.append('NA')

In [121]:
#creating dataframe
IMDB_TV=pd.DataFrame({"Name":Name,
                "Year Span":Year_Span,
                "Genre":Genre,
                "Run Time":Run_Time,
                "Ratings":Ratings,
                "Votes":Votes})
print('\033[1m'+'Top 100 most watched tv shows of all time IMDB :'+'\033[0m')
IMDB_TV

Top 100 most watched tv shows of all time IMDB :

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,091,448"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,180,937"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"989,713"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"293,020"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"252,197"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,213"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,531"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"198,553"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,593"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"245,472"

In [122]:
# Closing of Automated Window:

driver.close()

# Question 10. 

Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/
        
You have to find the following details:
    
A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

In [123]:
# Connecting to webdriver:
driver=webdriver.Chrome(r"C:\Users\Lenovo\chromedriver.exe")

# Opening 'https://github.com/' in chrome browser:
url='https://archive.ics.uci.edu/'
driver.get(url)
driver.maximize_window()

In [124]:
# Clicking on all datasets links
dataset=driver.find_element(By.XPATH,"//a[@href='datasets.php']")
dataset.click()

In [125]:
# Creating empty lists
Dataset =[]
Data_Type =[]
Task =[]
Attribute_Type =[]
No_of_Instances =[]
No_of_Attribute =[]
Year =[]

In [127]:
# Scraping DataSet Name via Xpath
try:
    dataset=driver.find_elements(By.XPATH,"//p[@class='normal']/b/a")
    for i in dataset:
        Dataset.append(i.text)
except NoSuchElementException:
    Dataset.append('NA')
    
# Scraping Data Type via Xpath
try:
    Type=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in Type[1:]:
        Data_Type.append(i.text)
except NoSuchElementException:
    Data_Type.append('NA')
    
# Scraping Task via Xpath
try:
    task=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('NA')
    
# Scraping Attribute_Type via Xpath
try:
    attribute_Type=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')
    for i in attribute_Type[1:]:
        Attribute_Type.append(i.text)
except NoSuchElementException:
    Attribute_Type.append('NA')
    
# Scraping No_of_Instances via Xpath
try:
    no_of_Instances=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]')
    for i in no_of_Instances[1:]:
        No_of_Instances.append(i.text)
except NoSuchElementException:
    No_of_Instances.append('NA')

# Scraping No_of_Attribute via Xpath
try:
    no_of_Attribute=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]')
    for i in no_of_Attribute[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('NA')
    
# Scraping Year via Xpath
try:
    year=driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]')
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('NA')

In [129]:
# Creating Data Frame for UCI Dataset
UCI_Dataset=pd.DataFrame({'DataSet Title':Dataset,
                'Data Type':Data_Type,
                'Task':Task,
                'Attribute Type':Attribute_Type,
                'No of Instances':No_of_Instances,
                'No of Attribute':No_of_Attribute,
                'Year':Year})
print('\033[1m'+' UCI Machine Learning Dataset:'+'\033[0m')
UCI_Dataset

 UCI Machine Learning Dataset:

,DataSet Title,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [130]:
# Closing of Automated Window:

driver.close()